import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';

export default defineConfig({
  site: 'https://www.omarzaghloul.com',
  output: 'static',
  trailingSlash: 'always',
  integrations: [
    tailwind({ applyBaseStyles: false }),
    // @astrojs/sitemap is incompatible with Astro 4.16 (astro:routes:resolved
    // hook not available, causing a crash at astro:build:done).
    // Sitemap is generated by the postbuild script instead — see scripts/generate-sitemap.mjs
  ],
});